baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aita-lab.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc
  - jemoji

paginate: 5
paginate_path: "/page/:num"

futrue: true

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Atom Feed
author:
  name: AiTA@FPTU

logo: /images/Logo_Wide.png
email: aita.fptu@gmail.com

feed:
  path: atom.xml

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed

# analytics:
#   provider: google
#   google:
#     tracking_id: G-1MH93MRZ7X
